export enum DriftType {
  SELECTOR_MISSING = 'SELECTOR_MISSING',
  REQUIRED_FIELD_MISSING = 'REQUIRED_FIELD_MISSING',
  SCHEMA_MISMATCH = 'SCHEMA_MISMATCH',
  LOW_YIELD = 'LOW_YIELD',
  CONTENT_STRUCTURE_CHANGED = 'CONTENT_STRUCTURE_CHANGED'
}
