export enum ExtractorType {
  RULE_BASED = 'RULE_BASED',
  JSON_PARSER = 'JSON_PARSER',
  CSV_PARSER = 'CSV_PARSER',
  NDJSON_PARSER = 'NDJSON_PARSER',
  AI_ASSISTED = 'AI_ASSISTED',
  MANUAL_REVIEW = 'MANUAL_REVIEW'
}
