export enum MergeProposalStatus {
  DRAFT = 'DRAFT',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  READY_FOR_DOMAIN_REVIEW = 'READY_FOR_DOMAIN_REVIEW',
  REJECTED = 'REJECTED',
  ACCEPTED_BY_DOMAIN = 'ACCEPTED_BY_DOMAIN',
}
