export enum SourceConnectorCategory {
  OFFICIAL_API = 'OFFICIAL_API',
  OFFICIAL_FEED = 'OFFICIAL_FEED',
  SITEMAP = 'SITEMAP',
  JSON_LD = 'JSON_LD',
  STATIC_HTML = 'STATIC_HTML',
  DOCUMENT = 'DOCUMENT',
  BROWSER_ASSISTED = 'BROWSER_ASSISTED',
  MANUAL_UPLOAD = 'MANUAL_UPLOAD'
}
