export enum SourceAccessClassification {
  PUBLIC_ALLOWED = 'PUBLIC_ALLOWED',
  PUBLIC_ROBOTS_RESTRICTED = 'PUBLIC_ROBOTS_RESTRICTED',
  AUTHORIZED_ACCOUNT = 'AUTHORIZED_ACCOUNT',
  DATA_AGREEMENT = 'DATA_AGREEMENT',
  MANUAL_ONLY = 'MANUAL_ONLY',
  BLOCKED = 'BLOCKED'
}
