export enum CareerJobStatus {
  DRAFT = 'DRAFT',
  READY_TO_REVIEW = 'READY_TO_REVIEW',
  READY_TO_PUBLISH = 'READY_TO_PUBLISH',
  PUBLISHED = 'PUBLISHED',
  EXPIRED = 'EXPIRED',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED'
}
