export enum AIRequestPurpose {
  TOOL_ASSISTANCE = 'TOOL_ASSISTANCE',
  IMPORT_CLASSIFICATION = 'IMPORT_CLASSIFICATION',
  CONTENT_DRAFT = 'CONTENT_DRAFT',
  RECOMMENDATION = 'RECOMMENDATION',
  TRANSLATION = 'TRANSLATION',
  SUMMARIZATION = 'SUMMARIZATION'
}
