export enum InternationalTestStatus {
  IMPORTED = 'IMPORTED',
  READY_TO_REVIEW = 'READY_TO_REVIEW',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  READY_TO_PUBLISH = 'READY_TO_PUBLISH',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
  REJECTED = 'REJECTED'
}

export enum InternationalTestCategory {
  LANGUAGE_PROFICIENCY = 'LANGUAGE_PROFICIENCY',
  UNDERGRAD_ADMISSION = 'UNDERGRAD_ADMISSION',
  GRAD_ADMISSION = 'GRAD_ADMISSION',
  PROFESSIONAL_LICENSING = 'PROFESSIONAL_LICENSING',
  ACADEMIC_PLACEMENT = 'ACADEMIC_PLACEMENT',
  OTHER = 'OTHER'
}

export enum InternationalTestCompletenessStatus {
  INCOMPLETE = 'INCOMPLETE',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  COMPLETE = 'COMPLETE'
}

export enum InternationalTestDeliveryMode {
  ONLINE = 'ONLINE',
  IN_PERSON = 'IN_PERSON',
  HYBRID = 'HYBRID'
}

export enum InternationalTestSourceType {
  OFFICIAL_PROVIDER = 'OFFICIAL_PROVIDER',
  AGGREGATOR = 'AGGREGATOR',
  UNIVERSITY = 'UNIVERSITY',
  OTHER = 'OTHER'
}

export enum InternationalTestSourceTrustLevel {
  AUTHORITATIVE = 'AUTHORITATIVE',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW'
}

export enum InternationalTestReadinessStatus {
  IMPORTED = 'IMPORTED',
  INCOMPLETE = 'INCOMPLETE',
  COMPLETE = 'COMPLETE',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  READY_TO_PUBLISH = 'READY_TO_PUBLISH',
  PUBLISHED = 'PUBLISHED',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED'
}

export enum InternationalTestValidationSeverity {
  ERROR = 'ERROR',
  WARNING = 'WARNING',
  INFO = 'INFO'
}
