export enum AssetLifecycleState {
  INITIATED = 'INITIATED',
  QUARANTINED = 'QUARANTINED',
  VALIDATING = 'VALIDATING',
  MALWARE_SCAN_FAILED = 'MALWARE_SCAN_FAILED',
  SANITIZING = 'SANITIZING',
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
  DELETED = 'DELETED',
  PURGED = 'PURGED'
}
