export enum CourseStatus {
  DRAFT = 'DRAFT',
  IMPORTED = 'IMPORTED',
  INCOMPLETE = 'INCOMPLETE',
  READY_TO_REVIEW = 'READY_TO_REVIEW',
  READY_TO_PUBLISH = 'READY_TO_PUBLISH',
  PUBLISHED = 'PUBLISHED',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED'
}
